### ISSUE TITLE
Incompatibility with Adobe Commerce Mercado Pago Plugin

### ISSUE THREAD

**Issue by 7LlantasManager** [developersalliance/module-table-rates#2]
Hi, this module is incompatible with Mercado Pago Plugin for Adobe Commerce.

The module conflicts with the Mercado Pago payment method, when trying to finalize any purchase in the checkout process, it throws the error: Entity 34 does not exist.

**Comment by oskarst** [comment]
> Hi, this module is incompatible with Mercado Pago Plugin for Adobe Commerce.
> 
> The module conflicts with the Mercado Pago payment method, when trying to finalize any purchase in the checkout process, it throws the error: Entity 34 does not exist.

@7LlantasManager Thanks for letting us know. Our plugin is open-source, so sometimes it might not work with every other plugin out there. 

If you need help, please email us at [hello@developers-alliance.com](mailto:hello@developers-alliance.com). We can offer support for Magento.
